# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20170620_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='uniqueId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
